// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuQMUeHtzwUlHl1jX98r2boXYfZ8Q4TV8',
    appId: '1:120256341252:web:7392525165ae8b6e4edc51',
    messagingSenderId: '120256341252',
    projectId: 'veridocs-rs',
    authDomain: 'veridocs-rs.firebaseapp.com',
    databaseURL: 'https://veridocs-rs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'veridocs-rs.appspot.com',
    measurementId: 'G-DT0S3YM9ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJLtC-F1HAPHvy3j2d3rzQJu4i6nd7aO0',
    appId: '1:120256341252:android:91cd63affa5a848b4edc51',
    messagingSenderId: '120256341252',
    projectId: 'veridocs-rs',
    databaseURL: 'https://veridocs-rs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'veridocs-rs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHz2XpGqsHFX3sfYybyPIcZZKs6OzXax8',
    appId: '1:120256341252:ios:533ecb25e97bfac64edc51',
    messagingSenderId: '120256341252',
    projectId: 'veridocs-rs',
    databaseURL: 'https://veridocs-rs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'veridocs-rs.appspot.com',
    androidClientId: '120256341252-ar3t4orpihi12v5mvsur386kn9r65dv8.apps.googleusercontent.com',
    iosClientId: '120256341252-r5gi7dgdvbkr6pf009c6r3kmh6lv2j47.apps.googleusercontent.com',
    iosBundleId: 'com.example.veridox',
  );
}
