// TODO: USER AUTHENTICATION CHANGES
// TODO: FORMS IMAGES WIDGET
// TODO: FORMS FILE WIDGET
// TODO: FORMS DETAILS PAGE
// TODO: FIELD VERIFIER PROFILE REFERENCE IN DATABASE
// TODO: DELETE ACCOUNT REQUEST / JOIN NEW AGENCY
