/// DONE: USER AUTHENTICATION CHANGES
/// DONE: FORMS IMAGES WIDGET
/// DONE: FORMS FILE WIDGET - VIEW FILE FUNCTIONALITY
/// DONE: FORMS DETAILS PAGE
/// DONE: FIELD VERIFIER PROFILE REFERENCE IN DATABASE
/// TODO: DELETE ACCOUNT REQUEST / JOIN NEW AGENCY -- PENDING
// TODO: MORE FORM WIDGETS- PAN, AADHAR, EMAIL,
